In [72]:
class Every:
    def __init__(self, every):
        self._every = every
        self._last = None

    def __call__(self, step):
        if not self._every:
            return 0
        if self._last is None:
            self._last = step
            return 1
        count = int((step - self._last) / self._every)
        self._last += self._every * count
        return count




In [73]:
total_steps = 50
train_every = Every(5)

for i in range(50):
    print( train_every(i) )



1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0


In [74]:
v1 = {}
v2 = {"a":1, "b":2, "c":3}
v3 = ({},{})
print(type(v1))
print(type(v2))
print(type(v3))

<class 'dict'>
<class 'dict'>
<class 'tuple'>


In [75]:
import torch
import torch.distributions as torchd

logits = torch.tensor([2.0, 0.5, -1.0])
dist = torchd.OneHotCategorical(logits=logits)

sample = dist.sample()
logp = dist.log_prob(sample)

print("sample:", sample)
print("log_prob:", logp)


sample: tensor([0., 1., 0.])
log_prob: tensor(-1.7413)


In [86]:
import torch
import torch.distributions as torchd

logits = torch.tensor([
    [2.0, 0.5, -1.0],
    [0.1, 1.2, 0.3]
])

dist = torchd.OneHotCategorical(logits=logits)
sample = dist.sample()
print(sample)
logp = -dist.log_prob(sample)

print(logp)
print(dist.entropy())
#dist
# batch0:
# [0.786 , 0.175 , 0.039]
#
# batch1:
# [0.191 , 0.575 , 0.234]

tensor([[1., 0., 0.],
        [0., 0., 1.]])
tensor([0.2413, 1.4536])
tensor([0.6216, 0.9744])


In [77]:
joint = torchd.Independent(dist, 1)
print(joint.entropy())
sample = joint.sample()
print(sample)
logp = joint.log_prob(sample)
print(logp)
#一起发生的概率

tensor(1.5960)
tensor([[1., 0., 0.],
        [0., 0., 1.]])
tensor(-1.6949)


In [78]:
import torch

logits = torch.tensor([
    [2.0, 0.5, -1.0],
    [0.1, 1.2, 0.3]
])
soft = torch.softmax(logits, dim=-1)
log_soft = torch.log(soft)

print("softmax:\n", soft)
print("\nlog_softmax:\n", log_soft)


softmax:
 tensor([[0.7856, 0.1753, 0.0391],
        [0.1914, 0.5749, 0.2337]])

log_softmax:
 tensor([[-0.2413, -1.7413, -3.2413],
        [-1.6536, -0.5536, -1.4536]])


In [79]:
flat_x = torch.tensor([1,2,3,4,5,6,7,8,9,10], dtype=torch.float)
q = torch.tensor([0.05,0.95])

torch.quantile(flat_x, q)

tensor([1.4500, 9.5500])

In [80]:
v1 = 0.37/9.41
print(v1)

0.039319872476089264


In [81]:
import torch
import torch.distributions as torchd

logits = torch.tensor([
    [2.0,0.5,-1.0],
    [0.1,1.2,0.3]
])

dist = torchd.OneHotCategorical(logits=logits)

print("dist entropy:")
print(dist.entropy())

joint = torchd.Independent(dist,1)

print("joint entropy:")
print(joint.entropy())

dist entropy:
tensor([0.6216, 0.9744])
joint entropy:
tensor(1.5960)
