In [3]:
class Every:
    def __init__(self, every):
        self._every = every
        self._last = None

    def __call__(self, step):
        if not self._every:
            return 0
        if self._last is None:
            self._last = step
            return 1
        count = int((step - self._last) / self._every)
        self._last += self._every * count
        return count




In [4]:
total_steps = 50
train_every = Every(5)

for i in range(50):
    print( train_every(i) )



1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
0


In [5]:
v1 = {}
v2 = {"a":1, "b":2, "c":3}
v3 = ({},{})
print(type(v1))
print(type(v2))
print(type(v3))

<class 'dict'>
<class 'dict'>
<class 'tuple'>


In [6]:
import torch
import torch.distributions as torchd

logits = torch.tensor([2.0, 0.5, -1.0])
dist = torchd.OneHotCategorical(logits=logits)

sample = dist.sample()
logp = dist.log_prob(sample)

print("sample:", sample)
print("log_prob:", logp)


sample: tensor([1., 0., 0.])
log_prob: tensor(-0.2413)


In [7]:
import torch
import torch.distributions as torchd

logits = torch.tensor([
    [2.0, 0.5, -1.0],
    [0.1, 1.2, 0.3]
])

dist = torchd.OneHotCategorical(logits=logits)
sample = dist.sample()
logp = dist.log_prob(sample)
print(sample)
print(logp)

tensor([[0., 1., 0.],
        [0., 1., 0.]])
tensor([-1.7413, -0.5536])


In [10]:
joint = torchd.Independent(dist, 1)
print(joint.entropy())
sample = joint.sample()
logp = joint.log_prob(sample)
print(logp)


tensor(1.5960)
tensor(-1.6949)


In [9]:
import torch

logits = torch.tensor([
    [2.0, 0.5, -1.0],
    [0.1, 1.2, 0.3]
])
soft = torch.softmax(logits, dim=-1)
log_soft = torch.log(soft)

print("softmax:\n", soft)
print("\nlog_softmax:\n", log_soft)



softmax:
 tensor([[0.7856, 0.1753, 0.0391],
        [0.1914, 0.5749, 0.2337]])

log_softmax:
 tensor([[-0.2413, -1.7413, -3.2413],
        [-1.6536, -0.5536, -1.4536]])
